build:
  nodes:
    coverage:
      services:
        elasticsearch: 6.4.0

      environment:
        variables:
          ELASTICSEARCH_HOSTS: http://127.0.0.1:9200

      cache:
        directories:
          - vendor/

      tests:
        stop_on_failure: true
        override:
          - command: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
            stop_on_failure: true
            coverage:
              file: build/logs/clover.xml
              format: clover

    analysis:
      tests:
        override:
          - 'php-scrutinizer-run --enable-security-analysis'
          - command: phpcs-run
            use_website_config: true